# Generated by Django 2.0.4 on 2018-04-29 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180429_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(db_column='train_stop', on_delete=django.db.models.deletion.CASCADE, to='api.Destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='meetup',
            field=models.ForeignKey(db_column='address', on_delete=django.db.models.deletion.CASCADE, to='api.Meetup'),
        ),
    ]
